### ISSUE TITLE
Slim linter?

### ISSUE THREAD

**Issue by noinkling** [SublimeLinter/SublimeLinter-haml#2]
I ask here because of the similarities, doesn't seem like it would be too difficult to adapt this to a [Slim](https://github.com/slim-template/slim) linter?

The binary supports the same options, i.e. `slimrb -c --stdin`. Output is a little different but doesn't look any more difficult to parse. Example:

```
Slim::Parser::SyntaxError: Unknown line indicator
  STDIN, Line 3, Column 0
    $%^#$%^DFSGHdfghdfggh
    ^
  Use --trace for backtrace.
```

**Comment by maletor** [comment]
This was made official last night:

https://github.com/AtomLinter/linter-slim
