### ISSUE TITLE
Incorrect version detection

### ISSUE THREAD

**Issue by Zyphrax** [SublimeLinter/SublimeLinter-haml#4]
SublimeLinter reports haml version 2.0.0 instead of 4.0.6

```
SublimeLinter: haml version query: /usr/bin/ruby /Users/Me/.gems/bin/haml --version 
SublimeLinter: haml version: 2.0.0 
SublimeLinter: WARNING: haml deactivated, version requirement (>= 4.0) not fulfilled by 2.0.0 
```

```
MyHost:~ Me$ haml --version
Haml 4.0.6
```

It almost seems to report my ruby version instead of my haml version.
Why is the haml command prefixed with `/usr/bin/ruby`?

**Comment by sirganya** [comment]
I fixed this by installing the latest version of ruby
```
rvm install ruby --latest
```
and then 

```
gem install haml
```

**Comment by sirganya** [comment]
removing and reinstalling the package worked for me.

**Comment by dgm** [comment]
I don't have haml 2.0.0 installed anywhere in any of my rvm trees, and I do have haml 4.0.5 installed in my ruby 2.0.0  tree.... and getting this error....

**Comment by EricaChua** [comment]
Having the same problem. Removing an reinstalling the package didn't worked for me...

**Comment by groteworld** [comment]
What is returned when you run the command statement below in the SublimeText console? What OS are you using? I'm not seeing the same issue, so it's hard for me to debug, any additional information is greatly appreciated.

```python
import subprocess; subprocess.check_output(['/usr/local/bin/haml --version'], shell=True)
```

**Comment by dgm** [comment]
A couple of different tries...  I have RVM installed, so you can't run haml directly - you have to go through the auto ruby file, which is what I see in the console logs.

>>> import subprocess; subprocess.check_output(['/Users/dmorton/.rvm/gems/ruby-2.0.0-p643/bin/haml --version'], shell=True)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command '['/Users/dmorton/.rvm/gems/ruby-2.0.0-p643/bin/haml --version']' returned non-zero exit status 127


>>> import subprocess; subprocess.check_output(['/Users/dmorton/.rvm/bin/rvm-auto-ruby /Users/dmorton/.rvm/gems/ruby-2.0.0-p643/bin/haml --version'], shell=True)
b'Haml 4.0.6\n'

**Comment by tiansivive** [comment]
Also having this issue.
Anybody managed to fix this?

**Comment by deritaufan** [comment]
Bum for the fix. I have the same error.

**Comment by braver** [comment]
We don’t do version checks anymore.
